apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secret.yaml
images:
- name: wuyadong1990/guestbook-demo
  newTag: 664783d8bfdf01d13cfb5b101a5ce1b6ba629cc7
